name: Demo Check

on:
  pull_request:
    branches: [main]

jobs:
  demo-check:
    name: Custom Commit Status
    runs-on: ubuntu-latest
    permissions:
      statuses: write  # Needed to post commit status

    steps:
      - uses: actions/checkout@v4

      - name: Validate branch prefix
        id: validate
        run: |
          BRANCH_NAME="${GITHUB_HEAD_REF:-${GITHUB_REF##*/}}"
          if [[ "$BRANCH_NAME" == demo-* ]]; then
            echo "status=success" >> "$GITHUB_OUTPUT"
          else
            echo "status=failure" >> "$GITHUB_OUTPUT"
          fi

      - name: Set commit status
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          STATUS: ${{ steps.validate.outputs.status }}
          SHA: ${{ github.sha }}
          REPO: ${{ github.repository }}
          RUN_ID: ${{ github.run_id }}
        run: |
          OWNER="${REPO%%/*}"
          REPO_NAME="${REPO##*/}"
          DESCRIPTION=$([ "$STATUS" = "success" ] && echo "Branch name is valid ✅" || echo "Branch must start with 'demo-' ❌")
          TARGET_URL="https://github.com/$REPO/actions/runs/$RUN_ID"

          curl -s -X POST "https://api.github.com/repos/$OWNER/$REPO_NAME/statuses/$SHA" \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            -d @- <<EOF
{
  "state": "$STATUS",
  "context": "Demo Check",
  "description": "$DESCRIPTION",
  "target_url": "$TARGET_URL"
}
EOF

      - name: Fail if branch is invalid
        if: steps.validate.outputs.status == 'failure'
        run: exit 1