name: Jira Task Checker

on:
  pull_request:
    types: [opened, synchronize, edited]

jobs:
  commit-check:
    name: commit-check
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate commit or branch
        id: validate
        run: |
          BRANCH="${{ github.head_ref }}"
          COMMITS=$(git log origin/"$BRANCH" --pretty=format:"%s" -n 10 || echo "")
          if [[ "$BRANCH" == devsre-* ]] || echo "$COMMITS" | grep -q "^devsre-"; then
            echo "status=success" >> $GITHUB_OUTPUT
            echo "desc=jira ticket validated" >> $GITHUB_OUTPUT
          else
            echo "status=failure" >> $GITHUB_OUTPUT
            echo "desc=Start branch or commit message with devsre-" >> $GITHUB_OUTPUT
          fi

      - name: Create custom commit check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHA: ${{ github.event.pull_request.head.sha }}
          STATUS: ${{ steps.validate.outputs.status }}
          DESC: ${{ steps.validate.outputs.desc }}
        run: |
          curl -s -X POST \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/check-runs \
            -d @- <<EOF
          {
            "name": "Jira task checker",
            "head_sha": "$SHA",
            "status": "completed",
            "conclusion": "$STATUS",
            "output": {
              "title": "Jira task checker",
              "summary": "$DESC"
            }
          }
EOF