name: Associate Jira Ticket #appear first of the commit check name

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
    branches:
      - main

jobs:
  Checker:
    name: ">" #appear in the middle of the commit check name
    uses: ./.github/workflows/commit.yaml